### ISSUE TITLE
Difference between GET request with /me/events and /me/calendars/<id>/events/<id>

### ISSUE THREAD

**Issue by dianadkle** [OfficeDev/microsoft-graph-docs#391]
After some testing, I noticed that both of the methods  /me/events and /me/calendars/<id>/events/<id> will return the same event object regardless of what calendar it is.  My question is in which cases would I then want to specify a calendar ID given that I can simply grab the same event with just an event ID?  Are event IDs also unique across all calendars?

**Comment by angelgolfer-ms** [comment]
@dianadkle , event IDs are unique across all calendars in the same mailbox.

If you are accessing a specific event, use /me/events/{event_id} and not /me/calendars/{calendar_id}/events/{events_id} because of the ambiguity of the latter.

You can, however, use /me/calendars/{calendar_id}/events to access the events collection of a specific calendar.

Cheers,

angelgolfer-ms
