### ISSUE TITLE
Missing Required Parameters for /calendarView

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/microsoft-graph-docs#57]
http://graph.microsoft.io/docs/api-reference/v1.0/api/user_list_calendarview lists no required parameters but requires a `StartDateTime` & `EndDateTime` - we should also document what time format to use (eg `ISO 8601`, `RFC 2822`, etc)

```
GET https://graph.microsoft.com/v1.0/me/calendarView

Error: 400 - Bad Request
 See Response Headers for details.
{
  "error": {
    "code": "ErrorInvalidParameter",
    "message": "This request requires a time window specified by the query string parameters StartDateTime and EndDateTime.",
    "innerError": {
      "request-id": "<request_id>",
      "date": "2015-12-02T05:39:51"
    }
  }
}
```

**Comment by iambmelt** [comment]
Looks great - thanks @martellaj @angelgolfer-ms :+1:

**Comment by marych** [comment]
StartDateTime and EndDateTime should be passed as query parameters and not in parenthesis, i.e. calendarView?startDateTime=startDateTime-value&endDateTime=endDateTime-value instead of calendarView(startDateTime=startDateTime-value, endDateTime=endDateTime-value)

The info about required query parameters was added to https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user_list_calendarview.md, but not https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group_list_calendarview.md and https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar_list_calendarview.md.

As I indicated in the answer to http://stackoverflow.com/questions/34189694/getting-a-list-of-instances-for-events-using-microsoft-graph https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event_list_instances.md also has StartDateTime and EndDateTime required parameters in the same format.

**Comment by iambmelt** [comment]
@marych 
>StartDateTime and EndDateTime should be passed as query parameters and not in parenthesis

I've seen in the documentation for [ReminderView](http://graph.microsoft.io/docs/api-reference/v1.0/api/user_reminderview) that the params are documented as being parenthetical (as opposed to query) - is this also a bug? Are both equivalent / legal?

/cc @martellaj @angelgolfer-ms

**Comment by marych** [comment]
ReminderView is a function and has the parameters explicitly defined in the schema/$metadata, so it uses the OData notation with parenthesis (http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398353). CalendarView is a navigation property and OData doesn't allow any parameters for navigation properties, so they're being passed as query parameters. Note that the required query parameters for CalendarView and Event.Instances navigations are not discoverable from $metadata, so it's particularly important to have them documented.
