### ISSUE TITLE
What should $count return

### ISSUE THREAD

**Issue by CodeMoggy** [OfficeDev/microsoft-graph-docs#74]
What should $count return?

https://graph.microsoft.io/docs/overview/query_parameters

I was expecting a number / size but the response returns a paged collection.

https://graph.microsoft.com/v1.0/me/contacts?$search=Arkle&$count

**Comment by martellaj** [comment]
Thanks for the feedback, @CodeMoggy. I've confirmed with Graph Explorer that using `$count` doesn't seem to change the request at all (at least with `/contacts`, which is what our documentation uses as an example.

@dkershaw10, @yinaa - is this expected behavior and a bug in the docs or a bug in the service?

**Comment by marych** [comment]
Bug in the docs, which is already fixed - see https://github.com/OfficeDev/microsoft-graph-docs/issues/126
